CREATE TABLE `mqtt_all` (
  `msg_id` BIGINT(20) AUTO_INCREMENT,
	`id`      SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
	`ts`      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`active`  TINYINT(4) NOT NULL DEFAULT '1',
	`topic`   TEXT NOT NULL,
	`value`   LONGTEXT NOT NULL,
	`qos`     TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`retain`  TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`msg_id` ),
	INDEX `id` (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

